### ISSUE TITLE
[Request] Placeholders in Private Message Configuration

### ISSUE THREAD

**Issue by Flexxxxx** [help-chat/DeluxeChat#3]
Currently with DeluxeChat whenever you send/receive a private message, it shows the sender/recipients nickname instead of their username. It's incredibly difficult to gauge who is actually speaking to you because on our server many players use a nickname vastly different to their actually username. 

If possible, could it be change so that we can use placeholders in our message configuration, so we can have the choice between %player_name% and %player_displayname%?

Thanks!

**Comment by Funny-cube** [comment]
You are currently able to it to any PlaceholderAPI placeholder,
Some ones you might find useful are here,
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player

%player_name% - For their registered username
%essentials_nickname% - For essentials nickname
And more on the link above

Thanks,
funnycube

**Comment by Flexxxxx** [comment]
It doesn’t work though, because %player_name% just returns the name of the person running the command.

**Comment by Andre601** [comment]
Just remember to use `recipient_<placeholder>%` for the person receiving the message.
So f.e. `%recipient_player_name%`
This will only work when bungeecord is disabled. Enabling this in the config only allows `%recipient%`
